# Notebook 03

# Silver Exposure Layer

## Objective

Transform the raw EM-DAT disaster dataset into a standardized analytical dataset containing cleaned historical flood events for India.

In [2]:
# ============================================================
# Notebook 03 : Silver Exposure Layer
# India Flood Risk Platform
# ============================================================

# Standard Library
from pathlib import Path

# Data Handling
import pandas as pd
import numpy as np

# Display
pd.set_option("display.max_columns", None)
pd.set_option("display.max_rows", 10)

print("Libraries loaded successfully!")

Libraries loaded successfully!

In [5]:
# ============================================================
# Project Paths
# ============================================================

PROJECT_ROOT = Path.cwd().parent

EMDAT_FILE = (
    PROJECT_ROOT
    / "data"
    / "raw"
    / "emdat"
    / "EMDAT_India_Floods_2000_2025.xlsx"
)

SILVER_DIR = (
    PROJECT_ROOT
    / "data"
    / "silver"
)

print("Project Root :", PROJECT_ROOT)
print("File Exists :", EMDAT_FILE.exists())

Project Root : d:\Work\Projects\India_Flood_Risk_Platform
File Exists : True

In [6]:
# ============================================================
# Load EM-DAT Dataset
# ============================================================

df = pd.read_excel(EMDAT_FILE)

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [7]:
# Shape

print(df.shape)

df.head()

(205, 47)

,DisNo.,Historic,Classification Key,Disaster Group,Disaster Subgroup,Disaster Type,Disaster Subtype,External IDs,Event Name,ISO,Country,Subregion,Region,Location,Origin,Associated Types,OFDA/BHA Response,Appeal,Declaration,AID Contribution ('000 US$),Magnitude,Magnitude Scale,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Injured,No. Affected,No. Homeless,Total Affected,Reconstruction Costs ('000 US$),"Reconstruction Costs, Adjusted ('000 US$)",Insured Damage ('000 US$),"Insured Damage, Adjusted ('000 US$)",Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",CPI,Admin Units,GADM Admin Units,Entry Date,Last Update
0,2010-0416-IND,No,nat-hyd-flo-riv,Natural,Hydrological,Flood,Riverine flood,NaN,NaN,IND,India,Southern Asia,Asia,Lakhimpur district (Assam province),Monsoonal rain,NaN,No,No,No,NaN,12555.0,Km2,26.235,92.25,Singora,2010,9,5.0,2010,9,17.0,NaN,NaN,30000.0,NaN,30000.0,NaN,NaN,NaN,NaN,NaN,NaN,67.731095,"[{""adm2_code"":70091,""adm2_name"":""Lakhimpur""}]","[{""gid_2"":""IND.4.20_1"",""migration_date"":""2025-...",2011-01-10,2025-12-20
1,2019-0331-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,India,Southern Asia,Asia,"Sitamarhi, Sheohar, East Champaran, Muzaffarpu...",Monsoon rain,"Slide (land, mud, snow, rock)",No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2019,7,14.0,2019,9,30.0,1900.0,NaN,3000000.0,NaN,3000000.0,NaN,NaN,200000.0,251855.0,10000000.0,12592748.0,79.410785,"[{""adm1_code"":1493,""adm1_name"":""Himachal Prade...","[{""gid_1"":""IND.13_1"",""migration_date"":""2025-12...",2019-07-15,2025-12-20
2,2018-0372-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,India,Southern Asia,Asia,"Punjab, Haryana states",NaN,"Slide (land, mud, snow, rock)",No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2018,9,23.0,2018,9,24.0,25.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,77.997265,"[{""adm1_code"":1492,""adm1_name"":""Haryana""},{""ad...","[{""gid_1"":""IND.12_1"",""migration_date"":""2025-12...",2018-10-11,2025-12-20
3,2018-0286-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),NaN,NaN,IND,India,Southern Asia,Asia,Odisha state,Heavy rains,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2018,7,20.0,2018,7,23.0,20.0,NaN,41430.0,NaN,41430.0,NaN,NaN,NaN,NaN,NaN,NaN,77.997265,"[{""adm1_code"":1504,""adm1_name"":""Orissa""}]","[{""gid_1"":""IND.26_1"",""migration_date"":""2025-12...",2018-08-09,2025-12-20
4,2021-0677-IND,No,nat-hyd-flo-flo,Natural,Hydrological,Flood,Flood (General),GLIDE:FL-2021-000161,NaN,IND,India,Southern Asia,Asia,"Idukki, Kottayam, Pathanamthitta, Kollam, Acha...",Heavy rains,NaN,No,No,No,NaN,NaN,Km2,NaN,NaN,NaN,2021,10,11.0,2021,10,20.0,39.0,NaN,3500.0,450.0,3950.0,NaN,NaN,NaN,NaN,NaN,NaN,84.166983,"[{""adm2_code"":17700,""adm2_name"":""Idukki""},{""ad...","[{""gid_2"":""IND.17.11_1"",""migration_date"":""2025...",2021-10-18,2025-12-20

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 47 columns):
 #   Column                                     Non-Null Count  Dtype
---  ------                                     --------------  -----
 0   DisNo.                                     205 non-null    str
 1   Historic                                   205 non-null    str
 2   Classification Key                         205 non-null    str
 3   Disaster Group                             205 non-null    str
 4   Disaster Subgroup                          205 non-null    str
 5   Disaster Type                              205 non-null    str
 6   Disaster Subtype                           205 non-null    str
 7   External IDs                               51 non-null     str
 8   Event Name                                 0 non-null      float64
 9   ISO                                        205 non-null    str
 10  Country                                    205 non-null    str
 11  Subregion                                  205 non-null    str
 12  Region                                     205 non-null    str
 13  Location                                   205 non-null    str
 14  Origin                                     175 non-null    str
 15  Associated Types                           67 non-null     str
 16  OFDA/BHA Response                          205 non-null    str
 17  Appeal                                     205 non-null    str
 18  Declaration                                205 non-null    str
 19  AID Contribution ('000 US$)                11 non-null     float64
 20  Magnitude                                  86 non-null     float64
 21  Magnitude Scale                            205 non-null    str
 22  Latitude                                   63 non-null     float64
 23  Longitude                                  63 non-null     float64
 24  River Basin                                70 non-null     str
 25  Start Year                                 205 non-null    int64
 26  Start Month                                205 non-null    int64
 27  Start Day                                  192 non-null    float64
 28  End Year                                   205 non-null    int64
 29  End Month                                  205 non-null    int64
 30  End Day                                    194 non-null    float64
 31  Total Deaths                               192 non-null    float64
 32  No. Injured                                30 non-null     float64
 33  No. Affected                               146 non-null    float64
 34  No. Homeless                               20 non-null     float64
 35  Total Affected                             172 non-null    float64
 36  Reconstruction Costs ('000 US$)            0 non-null      float64
 37  Reconstruction Costs, Adjusted ('000 US$)  0 non-null      float64
 38  Insured Damage ('000 US$)                  11 non-null     float64
 39  Insured Damage, Adjusted ('000 US$)        11 non-null     float64
 40  Total Damage ('000 US$)                    70 non-null     float64
 41  Total Damage, Adjusted ('000 US$)          70 non-null     float64
 42  CPI                                        205 non-null    float64
 43  Admin Units                                187 non-null    str
 44  GADM Admin Units                           187 non-null    str
 45  Entry Date                                 205 non-null    str
 46  Last Update                                205 non-null    str
dtypes: float64(19), int64(4), str(24)
memory usage: 335.7 KB

In [9]:
df.columns.tolist()

['DisNo.',
 'Historic',
 'Classification Key',
 'Disaster Group',
 'Disaster Subgroup',
 'Disaster Type',
 'Disaster Subtype',
 'External IDs',
 'Event Name',
 'ISO',
 'Country',
 'Subregion',
 'Region',
 'Location',
 'Origin',
 'Associated Types',
 'OFDA/BHA Response',
 'Appeal',
 'Declaration',
 "AID Contribution ('000 US$)",
 'Magnitude',
 'Magnitude Scale',
 'Latitude',
 'Longitude',
 'River Basin',
 'Start Year',
 'Start Month',
 'Start Day',
 'End Year',
 'End Month',
 'End Day',
 'Total Deaths',
 'No. Injured',
 'No. Affected',
 'No. Homeless',
 'Total Affected',
 "Reconstruction Costs ('000 US$)",
 "Reconstruction Costs, Adjusted ('000 US$)",
 "Insured Damage ('000 US$)",
 "Insured Damage, Adjusted ('000 US$)",
 "Total Damage ('000 US$)",
 "Total Damage, Adjusted ('000 US$)",
 'CPI',
 'Admin Units',
 'GADM Admin Units',
 'Entry Date',
 'Last Update']

In [10]:
# ============================================================
# Select Analytical Columns
# ============================================================

selected_columns = [

    # Identification
    "DisNo.",
    "Historic",

    # Disaster Classification
    "Disaster Type",
    "Disaster Subtype",

    # Geography
    "Country",
    "Location",
    "Latitude",
    "Longitude",
    "River Basin",

    # Event Dates
    "Start Year",
    "Start Month",
    "Start Day",
    "End Year",
    "End Month",
    "End Day",

    # Human Impact
    "Total Deaths",
    "No. Affected",
    "Total Affected",

    # Economic Impact
    "Total Damage ('000 US$)",
    "Total Damage, Adjusted ('000 US$)",

    # Administrative Units
    "Admin Units"
]

emdat = df[selected_columns].copy()

emdat.head()

,DisNo.,Historic,Disaster Type,Disaster Subtype,Country,Location,Latitude,Longitude,River Basin,Start Year,Start Month,Start Day,End Year,End Month,End Day,Total Deaths,No. Affected,Total Affected,Total Damage ('000 US$),"Total Damage, Adjusted ('000 US$)",Admin Units
0,2010-0416-IND,No,Flood,Riverine flood,India,Lakhimpur district (Assam province),26.235,92.25,Singora,2010,9,5.0,2010,9,17.0,NaN,30000.0,30000.0,NaN,NaN,"[{""adm2_code"":70091,""adm2_name"":""Lakhimpur""}]"
1,2019-0331-IND,No,Flood,Flood (General),India,"Sitamarhi, Sheohar, East Champaran, Muzaffarpu...",NaN,NaN,NaN,2019,7,14.0,2019,9,30.0,1900.0,3000000.0,3000000.0,10000000.0,12592748.0,"[{""adm1_code"":1493,""adm1_name"":""Himachal Prade..."
2,2018-0372-IND,No,Flood,Flood (General),India,"Punjab, Haryana states",NaN,NaN,NaN,2018,9,23.0,2018,9,24.0,25.0,NaN,NaN,NaN,NaN,"[{""adm1_code"":1492,""adm1_name"":""Haryana""},{""ad..."
3,2018-0286-IND,No,Flood,Flood (General),India,Odisha state,NaN,NaN,NaN,2018,7,20.0,2018,7,23.0,20.0,41430.0,41430.0,NaN,NaN,"[{""adm1_code"":1504,""adm1_name"":""Orissa""}]"
4,2021-0677-IND,No,Flood,Flood (General),India,"Idukki, Kottayam, Pathanamthitta, Kollam, Acha...",NaN,NaN,NaN,2021,10,11.0,2021,10,20.0,39.0,3500.0,3950.0,NaN,NaN,"[{""adm2_code"":17700,""adm2_name"":""Idukki""},{""ad..."

In [11]:
print(emdat.shape)

emdat.info()

(205, 21)
<class 'pandas.DataFrame'>
RangeIndex: 205 entries, 0 to 204
Data columns (total 21 columns):
 #   Column                             Non-Null Count  Dtype
---  ------                             --------------  -----
 0   DisNo.                             205 non-null    str
 1   Historic                           205 non-null    str
 2   Disaster Type                      205 non-null    str
 3   Disaster Subtype                   205 non-null    str
 4   Country                            205 non-null    str
 5   Location                           205 non-null    str
 6   Latitude                           63 non-null     float64
 7   Longitude                          63 non-null     float64
 8   River Basin                        70 non-null     str
 9   Start Year                         205 non-null    int64
 10  Start Month                        205 non-null    int64
 11  Start Day                          192 non-null    float64
 12  End Year                           205 non-null    int64
 13  End Month                          205 non-null    int64
 14  End Day                            194 non-null    float64
 15  Total Deaths                       192 non-null    float64
 16  No. Affected                       146 non-null    float64
 17  Total Affected                     172 non-null    float64
 18  Total Damage ('000 US$)            70 non-null     float64
 19  Total Damage, Adjusted ('000 US$)  70 non-null     float64
 20  Admin Units                        187 non-null    str
dtypes: float64(9), int64(4), str(8)
memory usage: 128.1 KB

In [12]:
# ============================================================
# Rename Columns
# ============================================================

emdat.rename(
    columns={
        "DisNo.": "event_id",
        "Historic": "historic",
        "Disaster Type": "disaster_type",
        "Disaster Subtype": "disaster_subtype",
        "Country": "country",
        "Location": "location",
        "Latitude": "latitude",
        "Longitude": "longitude",
        "River Basin": "river_basin",
        "Start Year": "start_year",
        "Start Month": "start_month",
        "Start Day": "start_day",
        "End Year": "end_year",
        "End Month": "end_month",
        "End Day": "end_day",
        "Total Deaths": "total_deaths",
        "No. Affected": "people_affected",
        "Total Affected": "total_affected",
        "Total Damage ('000 US$)": "damage_usd_000",
        "Total Damage, Adjusted ('000 US$)": "damage_adjusted_usd_000",
        "Admin Units": "admin_units"
    },
    inplace=True
)

emdat.head()

,event_id,historic,disaster_type,disaster_subtype,country,location,latitude,longitude,river_basin,start_year,start_month,start_day,end_year,end_month,end_day,total_deaths,people_affected,total_affected,damage_usd_000,damage_adjusted_usd_000,admin_units
0,2010-0416-IND,No,Flood,Riverine flood,India,Lakhimpur district (Assam province),26.235,92.25,Singora,2010,9,5.0,2010,9,17.0,NaN,30000.0,30000.0,NaN,NaN,"[{""adm2_code"":70091,""adm2_name"":""Lakhimpur""}]"
1,2019-0331-IND,No,Flood,Flood (General),India,"Sitamarhi, Sheohar, East Champaran, Muzaffarpu...",NaN,NaN,NaN,2019,7,14.0,2019,9,30.0,1900.0,3000000.0,3000000.0,10000000.0,12592748.0,"[{""adm1_code"":1493,""adm1_name"":""Himachal Prade..."
2,2018-0372-IND,No,Flood,Flood (General),India,"Punjab, Haryana states",NaN,NaN,NaN,2018,9,23.0,2018,9,24.0,25.0,NaN,NaN,NaN,NaN,"[{""adm1_code"":1492,""adm1_name"":""Haryana""},{""ad..."
3,2018-0286-IND,No,Flood,Flood (General),India,Odisha state,NaN,NaN,NaN,2018,7,20.0,2018,7,23.0,20.0,41430.0,41430.0,NaN,NaN,"[{""adm1_code"":1504,""adm1_name"":""Orissa""}]"
4,2021-0677-IND,No,Flood,Flood (General),India,"Idukki, Kottayam, Pathanamthitta, Kollam, Acha...",NaN,NaN,NaN,2021,10,11.0,2021,10,20.0,39.0,3500.0,3950.0,NaN,NaN,"[{""adm2_code"":17700,""adm2_name"":""Idukki""},{""ad..."

In [13]:
# ============================================================
# Missing Value Analysis
# ============================================================

missing = pd.DataFrame({
    "Missing Values": emdat.isna().sum(),
    "Percentage": (
        emdat.isna().mean() * 100
    ).round(2)
})

missing.sort_values(
    "Percentage",
    ascending=False
)

                         Missing Values  Percentage
latitude                            142       69.27
longitude                           142       69.27
river_basin                         135       65.85
damage_adjusted_usd_000             135       65.85
damage_usd_000                      135       65.85
...                                 ...         ...
location                              0        0.00
end_year                              0        0.00
start_month                           0        0.00
start_year                            0        0.00
end_month                             0        0.00

[21 rows x 2 columns]

In [14]:
# ============================================================
# Data Types
# ============================================================

emdat.dtypes

event_id                       str
historic                       str
disaster_type                  str
disaster_subtype               str
country                        str
                            ...
people_affected            float64
total_affected             float64
damage_usd_000             float64
damage_adjusted_usd_000    float64
admin_units                    str
Length: 21, dtype: object

In [15]:
# ============================================================
# Fill Missing Human Impact Values
# ============================================================

impact_columns = [
    "total_deaths",
    "people_affected",
    "total_affected"
]

emdat[impact_columns] = (
    emdat[impact_columns]
    .fillna(0)
)

emdat[impact_columns].isna().sum()

total_deaths       0
people_affected    0
total_affected     0
dtype: int64

In [16]:
# ============================================================
# Create Event Dates
# ============================================================

emdat["start_date"] = pd.to_datetime(
    dict(
        year=emdat["start_year"],
        month=emdat["start_month"],
        day=emdat["start_day"].fillna(1)
    ),
    errors="coerce"
)

emdat["end_date"] = pd.to_datetime(
    dict(
        year=emdat["end_year"],
        month=emdat["end_month"],
        day=emdat["end_day"].fillna(1)
    ),
    errors="coerce"
)

emdat[
    [
        "start_date",
        "end_date"
    ]
].head()

  start_date   end_date
0 2010-09-05 2010-09-17
1 2019-07-14 2019-09-30
2 2018-09-23 2018-09-24
3 2018-07-20 2018-07-23
4 2021-10-11 2021-10-20

In [17]:
# ============================================================
# Event Duration
# ============================================================

emdat["duration_days"] = (
    emdat["end_date"] -
    emdat["start_date"]
).dt.days + 1

emdat[
    [
        "event_id",
        "start_date",
        "end_date",
        "duration_days"
    ]
].head()

        event_id start_date   end_date  duration_days
0  2010-0416-IND 2010-09-05 2010-09-17             13
1  2019-0331-IND 2019-07-14 2019-09-30             79
2  2018-0372-IND 2018-09-23 2018-09-24              2
3  2018-0286-IND 2018-07-20 2018-07-23              4
4  2021-0677-IND 2021-10-11 2021-10-20             10

In [18]:
# ============================================================
# Organize Final Dataset
# ============================================================

emdat = emdat[
    [

        # Event
        "event_id",
        "historic",

        # Classification
        "disaster_type",
        "disaster_subtype",

        # Geography
        "country",
        "location",
        "river_basin",
        "latitude",
        "longitude",
        "admin_units",

        # Dates
        "start_date",
        "end_date",
        "duration_days",

        # Original Date Components
        "start_year",
        "start_month",
        "start_day",
        "end_year",
        "end_month",
        "end_day",

        # Human Impact
        "total_deaths",
        "people_affected",
        "total_affected",

        # Economic Impact
        "damage_usd_000",
        "damage_adjusted_usd_000"
    ]
]

emdat.head()

,event_id,historic,disaster_type,disaster_subtype,country,location,river_basin,latitude,longitude,admin_units,start_date,end_date,duration_days,start_year,start_month,start_day,end_year,end_month,end_day,total_deaths,people_affected,total_affected,damage_usd_000,damage_adjusted_usd_000
0,2010-0416-IND,No,Flood,Riverine flood,India,Lakhimpur district (Assam province),Singora,26.235,92.25,"[{""adm2_code"":70091,""adm2_name"":""Lakhimpur""}]",2010-09-05,2010-09-17,13,2010,9,5.0,2010,9,17.0,0.0,30000.0,30000.0,NaN,NaN
1,2019-0331-IND,No,Flood,Flood (General),India,"Sitamarhi, Sheohar, East Champaran, Muzaffarpu...",NaN,NaN,NaN,"[{""adm1_code"":1493,""adm1_name"":""Himachal Prade...",2019-07-14,2019-09-30,79,2019,7,14.0,2019,9,30.0,1900.0,3000000.0,3000000.0,10000000.0,12592748.0
2,2018-0372-IND,No,Flood,Flood (General),India,"Punjab, Haryana states",NaN,NaN,NaN,"[{""adm1_code"":1492,""adm1_name"":""Haryana""},{""ad...",2018-09-23,2018-09-24,2,2018,9,23.0,2018,9,24.0,25.0,0.0,0.0,NaN,NaN
3,2018-0286-IND,No,Flood,Flood (General),India,Odisha state,NaN,NaN,NaN,"[{""adm1_code"":1504,""adm1_name"":""Orissa""}]",2018-07-20,2018-07-23,4,2018,7,20.0,2018,7,23.0,20.0,41430.0,41430.0,NaN,NaN
4,2021-0677-IND,No,Flood,Flood (General),India,"Idukki, Kottayam, Pathanamthitta, Kollam, Acha...",NaN,NaN,NaN,"[{""adm2_code"":17700,""adm2_name"":""Idukki""},{""ad...",2021-10-11,2021-10-20,10,2021,10,11.0,2021,10,20.0,39.0,3500.0,3950.0,NaN,NaN

In [19]:
# ============================================================
# Validation
# ============================================================

print("=" * 60)
print("EM-DAT SILVER VALIDATION")
print("=" * 60)

print("Rows :", len(emdat))
print("Columns :", len(emdat.columns))

print("\nDate Range")
print(emdat["start_date"].min())
print(emdat["end_date"].max())

print("\nMissing Start Dates")
print(emdat["start_date"].isna().sum())

print("\nDuplicate Event IDs")
print(emdat["event_id"].duplicated().sum())

============================================================
EM-DAT SILVER VALIDATION
============================================================
Rows : 205
Columns : 24

Date Range
2000-06-10 00:00:00
2025-10-07 00:00:00

Missing Start Dates
0

Duplicate Event IDs
0

In [20]:
# ============================================================
# Export Silver Dataset
# ============================================================

silver_file = (
    SILVER_DIR /
    "silver_emdat_events.parquet"
)

emdat.to_parquet(
    silver_file,
    index=False
)

print("Silver EM-DAT exported successfully!")
print(silver_file)

Silver EM-DAT exported successfully!
d:\Work\Projects\India_Flood_Risk_Platform\data\silver\silver_emdat_events.parquet

In [21]:
# ============================================================
# Engineering Summary
# ============================================================

print("=" * 60)
print("SILVER EXPOSURE LAYER")
print("=" * 60)

print(f"Flood Events           : {len(emdat):,}")
print(f"Variables              : {len(emdat.columns)}")
print(f"Countries              : {emdat['country'].nunique()}")
print(f"Date Range             : {emdat['start_year'].min()} - {emdat['end_year'].max()}")

print("\nOutputs")
print("----------------------")
print("silver_emdat_events.parquet")

============================================================
SILVER EXPOSURE LAYER
============================================================
Flood Events           : 205
Variables              : 24
Countries              : 1
Date Range             : 2000 - 2025

Outputs
----------------------
silver_emdat_events.parquet